spring:
  # Configuração da Fonte de Dados (Datasource)
  #Baixar o banco de dados PostgresSql, configurar username a senha para integrar com a aplicação  
  datasource:
    url: jdbc:postgresql://localhost:5432/nome_do_seu_banco
    username: seu_usuario_postgres 
    password: sua_senha_postgres
    driver-class-name: org.postgresql.Driver
  
  # Configuração do JPA (Java Persistence API)
  jpa:
    show-sql: true # Mostra as queries SQL geradas no console
    hibernate:
      # Define a política de DDL (Data Definition Language)
      # 'update' é comum para desenvolvimento. Use 'none' ou 'validate' em produção.
      ddl-auto: update 
    properties:
      hibernate:
        # Define o dialeto específico do PostgreSQL para otimizar as queries
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuração do Servidor (opcional, mas bom ter para saber a porta)
server:
  port: 8080